[project]
name = 'Public-Fund-Allocation'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.budget-approval]
path = 'contracts/budget-approval.clar'
clarity_version = 2
epoch = 2.5

[contracts.expenditure-tracking]
path = 'contracts/expenditure-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.procurement-verification]
path = 'contracts/procurement-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
